/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */
declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;
    componentOnReady(done: (ele?: this) => void): void;
  }

  interface HTMLAttributes {}
}

import 'ionicons';
import '@ionic/core';


import {
  MadnessFeedback as MadnessFeedback
} from './components/madness-feedback/madness-feedback';

declare global {
  interface HTMLMadnessFeedbackElement extends MadnessFeedback, HTMLStencilElement {
  }
  var HTMLMadnessFeedbackElement: {
    prototype: HTMLMadnessFeedbackElement;
    new (): HTMLMadnessFeedbackElement;
  };
  interface HTMLElementTagNameMap {
    "madness-feedback": HTMLMadnessFeedbackElement;
  }
  interface ElementTagNameMap {
    "madness-feedback": HTMLMadnessFeedbackElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "madness-feedback": JSXElements.MadnessFeedbackAttributes;
    }
  }
  namespace JSXElements {
    export interface MadnessFeedbackAttributes extends HTMLAttributes {
      title?: string;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }
